### ISSUE TITLE
Introduction to Deep Learning Using Tensorflow and Keras

### ISSUE THREAD

**Issue by lfunderburk** [sciprog-sfu/sciprog-sfu.github.io#218]
## Description

In this workshop I provide a case study of developing deep learning neural network model with Python in Google Colaboratory or Colab. I will show how to use Tensorflow and Keras to create a very simple deep neural net. It requires no setup and runs fully in cloud. It does not matter whether you are using a Mac or a Windows computer, having a google account to sign in to Google is enough.

## Requirements
Bring your own laptop.
For this workshop you need to be familiar with:
1) basic machine learning concepts,
2) Python,
3) basic operations on data using numpy, Pandas, and Scikit-learn packages.

## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, November 19, 12:00pm - 1:30pm

## Registration

https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/34817

**Comment by adwiputra** [comment]
Hi,

I am Adrian Dwiputra, a Master's student in the Geography Department at UBC. I find this upcoming event really interesting because it is an excellent opportunity to learn more about deep learning. I am currently developing my research proposal and I think exploring the potential implementation of deep learning in the field of remote sensing and spatial analysis is a very exciting topic.

On the registration page, however, I learned that it is reserved only for Simon Fraser University students. Is there such a possibility to have a tiny space for a student from the neighboring university to participate?

I really look forward to hearing from you. For your kind considerations, thank you very much in advance!

Best regards,
Adrian

**Comment by lfunderburk** [comment]
Hello Adrian, 

Thank you for your message. 

I have put a request to the Research Commons to facilitate your participation in the workshop. 

What is your email address? We might need to set up a WiFi guest account for you. 

All the best,

Laura Gutierrez Funderburk

**Comment by adwiputra** [comment]
Hi Laura,

Thank you very much for kindly facilitating such a request! I hope it causes no significant trouble for nobody. My email is f.adrian.dwiputra@gmail.com or a.dwiputra@alumni.ubc.ca.

Best regards,
Adrian

**Comment by lfunderburk** [comment]
Hi Adrian, 

It is not a problem at all :).

From our end, you are welcome to join. We will have an attendance sheet onsite - you can add your name and affiliation the day of the workshop. 

Regarding wireless access, you can access the network via Eduroam. It seems like you have an Alumni account. Please ensure you are able to log in to Eduroam using it. 

More info here 

https://it.ubc.ca/services/email-voice-internet/wireless-internet-access/how-access-eduroam

Let me know if you have any questions. 

Look forward to meeting you!

Laura

**Comment by adwiputra** [comment]
Hi Laura,

Thanks for the wonderful information and for so welcoming! I am so happy to be able to join.

I have tested Eduroam connection and now I can confirm that I can log in.

Really look forward to meeting and learning  with you!
Adrian

**Comment by lfunderburk** [comment]
Hi Adrian, 

Happy to have you join. 

To prep for the workshop, please install the software listed here under the Setup section:

https://lfunderburk.github.io/2019-10-19-sfu-BashPythonGit/ 

Additionally, install the following Python dependencies:

- Matplotlib
- Pandas
- Numpy

**Comment by adwiputra** [comment]
Hi Laura,

Roger, that! I have them installed on my laptop now.

Cheers!
